/**
 * Audit all exam questions for English grammar errors.
 * Focuses on: missing possessive 's, article errors, subject-verb agreement, wrong prepositions.
 *
 * Usage:
 *   OPENAI_API_KEY=sk-... npx ts-node -r dotenv/config scripts/audit-questions.ts
 *
 * Output: SQL UPDATE statements printed to stdout (review before applying).
 * Redirect to file:  ... > fixes.sql
 */

import OpenAI from 'openai';
import { createClient } from '@supabase/supabase-js';

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
);

interface DbQuestion {
  id: string;
  type: string;
  difficulty_level: number;
  text: string;
  options: { id: string; text: string }[];
  correct_answer: number;
}

interface AuditResult {
  id: string;
  has_error: boolean;
  fixed_text?: string;
  fixed_options?: { id: string; text: string }[];
  errors?: string[];
}

const SYSTEM_PROMPT = `You are an expert English grammar checker for AMIRAM/AMIRET exam questions (Israeli university English placement test).
Your task: check if the given exam question has any English grammar errors.

Focus on these common errors:
1. Missing possessive apostrophe 's (e.g. "The company strategy" → "The company's strategy")
2. Missing articles (a/an/the)
3. Subject-verb agreement errors
4. Wrong prepositions
5. Dangling modifiers or unclear references
6. Inconsistent tense

IMPORTANT:
- These are AMIRET questions, so blanks (___) are intentional — do NOT flag them as errors
- Only flag REAL grammatical errors in the stem sentence or answer options
- If the question is grammatically correct, say so
- Return JSON only, no explanation outside JSON

Return JSON in this exact format:
{
  "has_error": true/false,
  "errors": ["description of error 1", ...],  // empty array if no errors
  "fixed_text": "corrected question text",     // same as input if no error
  "fixed_options": [{"id":"a","text":"..."},...] // same as input if no option errors
}`;

async function auditQuestion(q: DbQuestion): Promise<AuditResult> {
  const optionsText = q.options.map(o => `(${o.id}) ${o.text}`).join('\n');
  const userMessage = `Question ID: ${q.id}
Type: ${q.type} | Difficulty: ${q.difficulty_level}

Question text:
"${q.text}"

Options:
${optionsText}

Correct answer index: ${q.correct_answer}`;

  const response = await openai.chat.completions.create({
    model: 'gpt-4o-mini',
    messages: [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: userMessage },
    ],
    temperature: 0,
    response_format: { type: 'json_object' },
  });

  const content = response.choices[0].message.content ?? '{}';
  const parsed = JSON.parse(content) as {
    has_error: boolean;
    errors?: string[];
    fixed_text?: string;
    fixed_options?: { id: string; text: string }[];
  };

  return {
    id: q.id,
    has_error: parsed.has_error ?? false,
    fixed_text: parsed.fixed_text,
    fixed_options: parsed.fixed_options,
    errors: parsed.errors ?? [],
  };
}

function escapeSQL(s: string): string {
  return s.replace(/'/g, "''");
}

async function main() {
  console.error('Fetching all questions from Supabase...');
  const { data: questions, error } = await supabase
    .from('questions')
    .select('id, type, difficulty_level, text, options, correct_answer')
    .order('type')
    .order('difficulty_level');

  if (error || !questions) {
    console.error('Error fetching questions:', error);
    process.exit(1);
  }

  console.error(`Found ${questions.length} questions. Starting audit...`);

  const BATCH = 5; // questions per API call (to avoid rate limits)
  const fixes: AuditResult[] = [];
  let processed = 0;

  for (let i = 0; i < questions.length; i += BATCH) {
    const batch = questions.slice(i, i + BATCH) as DbQuestion[];
    const results = await Promise.all(batch.map(q => auditQuestion(q)));

    for (const r of results) {
      if (r.has_error) {
        fixes.push(r);
        const q = batch.find(b => b.id === r.id)!;
        console.error(`  ERROR in ${q.type} L${q.difficulty_level}: ${r.errors?.join('; ')}`);
      }
    }

    processed += batch.length;
    if (processed % 50 === 0) {
      console.error(`Progress: ${processed}/${questions.length}...`);
    }

    // Rate limit pause
    await new Promise(r => setTimeout(r, 300));
  }

  console.error(`\nFound ${fixes.length} questions with errors.\n`);

  // Output SQL UPDATE statements
  if (fixes.length === 0) {
    console.log('-- No errors found!');
    return;
  }

  console.log('-- Auto-generated by audit-questions.ts');
  console.log('-- Review each UPDATE carefully before applying!\n');

  for (const fix of fixes) {
    const q = (questions as DbQuestion[]).find(q => q.id === fix.id)!;
    const lines: string[] = [`-- ${q.type} L${q.difficulty_level}: ${fix.errors?.join('; ')}`];

    const textChanged = fix.fixed_text && fix.fixed_text !== q.text;
    const optionsChanged = fix.fixed_options &&
      JSON.stringify(fix.fixed_options) !== JSON.stringify(q.options);

    if (textChanged || optionsChanged) {
      let update = `UPDATE questions SET `;
      const parts: string[] = [];

      if (textChanged) {
        parts.push(`text = '${escapeSQL(fix.fixed_text!)}'`);
      }
      if (optionsChanged) {
        parts.push(`options = '${escapeSQL(JSON.stringify(fix.fixed_options))}'::jsonb`);
      }

      update += parts.join(', ');
      update += ` WHERE id = '${fix.id}';`;
      lines.push(update);
    } else {
      lines.push(`-- (No text change needed for ${fix.id})`);
    }

    console.log(lines.join('\n') + '\n');
  }
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
